### ISSUE TITLE
image captions styling

### ISSUE THREAD

**Issue by darebrawley** [GSAPP-CDP/Smorgasbord#14]
style/ability to add image captions (especially for left/right images)

**Comment by dantaeyoung** [comment]
Closed in #19.


Captions can be created by putting a line in asterisks, immediately after the image (without a line inbetween). Example:

```
![drawing_restraint.jpg](images/drawing_restraint_10.jpg)
*Matthew Barney, DRAWING RESTRAINT 10, 2005*
```
